/*
 * xg_syscall.c: the guest's Linux system calls, performed on Darwin.
 *
 * The guest's musl makes AArch64 Linux system calls (upstream's
 * port/android/guest/runtime/guest_syscall.c). Numbers come from the guest
 * build's own bits/syscall.h (xg_linux_nr.h, generated by the build script).
 * Flags, structures and errno values are converted here; guest pointers are
 * offsets into guest memory.
 */
#include "xg_host.h"
#include "xg_linux_nr.h"

#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <mach/mach_time.h>
#include <os/os_sync_wait_on_address.h>
#include <poll.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/sysctl.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <time.h>
#include <unistd.h>

__thread int xg_errno;

/* ---------- errno */

int xg_linux_errno(int e)
{
	switch (e)
	{
	case EAGAIN: return 11;
	case EDEADLK: return 35;
	case ENAMETOOLONG: return 36;
	case ENOLCK: return 37;
	case ENOSYS: return 38;
	case ENOTEMPTY: return 39;
	case ELOOP: return 40;
	case ENOMSG: return 42;
	case EOVERFLOW: return 75;
	case EILSEQ: return 84;
	case ENOTSOCK: return 88;
	case EDESTADDRREQ: return 89;
	case EMSGSIZE: return 90;
	case EPROTOTYPE: return 91;
	case ENOPROTOOPT: return 92;
	case EPROTONOSUPPORT: return 93;
	case EOPNOTSUPP: return 95;
	case EAFNOSUPPORT: return 97;
	case EADDRINUSE: return 98;
	case EADDRNOTAVAIL: return 99;
	case ENETDOWN: return 100;
	case ENETUNREACH: return 101;
	case ENETRESET: return 102;
	case ECONNABORTED: return 103;
	case ECONNRESET: return 104;
	case ENOBUFS: return 105;
	case EISCONN: return 106;
	case ENOTCONN: return 107;
	case ETIMEDOUT: return 110;
	case ECONNREFUSED: return 111;
	case EHOSTDOWN: return 112;
	case EHOSTUNREACH: return 113;
	case EALREADY: return 114;
	case EINPROGRESS: return 115;
	case ECANCELED: return 125;
	default: return e <= 34 ? e : 5; /* 1-34 agree; anything else is EIO */
	}
}

int xh_host_errno(void) { return xg_errno; }

static long result_of(long value)
{
	return value == -1 ? -xg_linux_errno(errno) : value;
}

/* ---------- logging */

static pthread_mutex_t log_lock = PTHREAD_MUTEX_INITIALIZER;

void xg_log(const char *format, ...)
{
	va_list arguments;
	pthread_mutex_lock(&log_lock);
	fputs("[xbox] ", stderr);
	va_start(arguments, format);
	vfprintf(stderr, format, arguments);
	va_end(arguments);
	fputc('\n', stderr);
	pthread_mutex_unlock(&log_lock);
}

void xg_fatal(const char *format, ...)
{
	va_list arguments;
	pthread_mutex_lock(&log_lock);
	fputs("[xbox] fatal: ", stderr);
	va_start(arguments, format);
	vfprintf(stderr, format, arguments);
	va_end(arguments);
	fputc('\n', stderr);
	pthread_mutex_unlock(&log_lock);
	abort();
}

void xh_host_log(int priority, uint32_t text)
{
	xg_log("%s%s", priority >= 6 ? "error: " : priority == 5 ? "warning: " : "", G(const char *, text));
}

void xh_host_abort(uint32_t reason)
{
	xg_fatal("guest abort: %s", reason ? G(const char *, reason) : "(no reason)");
}

void xh_host_exit(int code)
{
	xg_log("guest exit %d", code);
	fflush(NULL);
	exit(code);
}

/* ---------- structures */

struct l_timespec { int32_t seconds, nanoseconds; };
struct l_iovec { uint32_t base, length; };
struct l_kstat {
	uint64_t dev, ino; uint32_t mode, nlink, uid, gid; uint64_t rdev, pad; int64_t size;
	int32_t blksize, pad2; int64_t blocks, atime, atime_ns, mtime, mtime_ns, ctime, ctime_ns; uint32_t unused[2];
};

static int timespec_in(uint32_t address, struct timespec *out)
{
	if (!address)
		return 0;
	out->tv_sec = G(struct l_timespec *, address)->seconds;
	out->tv_nsec = G(struct l_timespec *, address)->nanoseconds;
	return 1;
}

static void timespec_out(uint32_t address, const struct timespec *value)
{
	if (!address)
		return;
	G(struct l_timespec *, address)->seconds = (int32_t)value->tv_sec;
	G(struct l_timespec *, address)->nanoseconds = (int32_t)value->tv_nsec;
}

static void kstat_out(uint32_t address, const struct stat *s)
{
	struct l_kstat *k = G(struct l_kstat *, address);
	memset(k, 0, sizeof(*k));
	k->dev = (uint64_t)s->st_dev;
	k->ino = s->st_ino;
	k->mode = s->st_mode; /* the S_IF* and permission bits agree */
	k->nlink = s->st_nlink;
	k->uid = s->st_uid;
	k->gid = s->st_gid;
	k->rdev = (uint64_t)s->st_rdev;
	k->size = s->st_size;
	k->blksize = s->st_blksize;
	k->blocks = s->st_blocks;
	k->atime = s->st_atimespec.tv_sec;
	k->atime_ns = s->st_atimespec.tv_nsec;
	k->mtime = s->st_mtimespec.tv_sec;
	k->mtime_ns = s->st_mtimespec.tv_nsec;
	k->ctime = s->st_ctimespec.tv_sec;
	k->ctime_ns = s->st_ctimespec.tv_nsec;
}

static int dirfd_in(long long fd) { return (int)fd == -100 ? AT_FDCWD : (int)fd; }

static int open_flags(int l)
{
	int d = l & 3;
	if (l & 0100) d |= O_CREAT;
	if (l & 0200) d |= O_EXCL;
	if (l & 0400) d |= O_NOCTTY;
	if (l & 01000) d |= O_TRUNC;
	if (l & 02000) d |= O_APPEND;
	if (l & 04000) d |= O_NONBLOCK;
	if (l & 040000) d |= O_DIRECTORY;
	if (l & 0100000) d |= O_NOFOLLOW;
	if (l & 02000000) d |= O_CLOEXEC;
	return d;
}

static int status_flags_out(int d)
{
	int l = d & 3;
	if (d & O_APPEND) l |= 02000;
	if (d & O_NONBLOCK) l |= 04000;
	return l;
}

static int at_flags(int l)
{
	int d = 0;
	if (l & 0x100) d |= AT_SYMLINK_NOFOLLOW;
	if (l & 0x200) d |= AT_REMOVEDIR;
	return d;
}

/* ---------- console */

static void console(int fd, const char *bytes, size_t size)
{
	pthread_mutex_lock(&log_lock);
	fwrite(bytes, 1, size, fd == 2 ? stderr : stdout);
	fflush(fd == 2 ? stderr : stdout);
	pthread_mutex_unlock(&log_lock);
}

static long vector_io(int fd, uint32_t vector, int count, int64_t offset, int positional, int writing)
{
	struct iovec host[64];
	const struct l_iovec *guest = G(const struct l_iovec *, vector);
	int index;
	if (count < 0 || count > 64)
		return -22;
	for (index = 0; index < count; index++)
	{
		host[index].iov_base = G(void *, guest[index].base);
		host[index].iov_len = guest[index].length;
	}
	if (writing && (fd == 1 || fd == 2))
	{
		long total = 0;
		for (index = 0; index < count; index++)
		{
			console(fd, host[index].iov_base, host[index].iov_len);
			total += (long)host[index].iov_len;
		}
		return total;
	}
	if (writing)
		return result_of(positional ? pwritev(fd, host, count, offset) : writev(fd, host, count));
	return result_of(positional ? preadv(fd, host, count, offset) : readv(fd, host, count));
}

/* ---------- directories: getdents64 over a DIR * kept per descriptor */

#define DIR_SLOTS 64
static struct { int fd; DIR *dir; } dirs[DIR_SLOTS];
static pthread_mutex_t dir_lock = PTHREAD_MUTEX_INITIALIZER;

static DIR *dir_for(int fd)
{
	int index, free_slot = -1;
	DIR *dir;
	for (index = 0; index < DIR_SLOTS; index++)
	{
		if (dirs[index].dir && dirs[index].fd == fd)
			return dirs[index].dir;
		if (!dirs[index].dir && free_slot < 0)
			free_slot = index;
	}
	if (free_slot < 0)
		return NULL;
	dir = fdopendir(dup(fd));
	if (dir)
	{
		dirs[free_slot].fd = fd;
		dirs[free_slot].dir = dir;
	}
	return dir;
}

static void dir_forget(int fd)
{
	int index;
	pthread_mutex_lock(&dir_lock);
	for (index = 0; index < DIR_SLOTS; index++)
	{
		if (dirs[index].dir && dirs[index].fd == fd)
		{
			closedir(dirs[index].dir);
			dirs[index].dir = NULL;
		}
	}
	pthread_mutex_unlock(&dir_lock);
}

static long getdents64(int fd, uint32_t buffer, uint32_t size)
{
	uint8_t *out = G(uint8_t *, buffer);
	uint32_t used = 0;
	DIR *dir;
	pthread_mutex_lock(&dir_lock);
	dir = dir_for(fd);
	if (!dir)
	{
		pthread_mutex_unlock(&dir_lock);
		return -9;
	}
	for (;;)
	{
		long position = telldir(dir);
		struct dirent *entry;
		size_t name = 0, length;
		errno = 0;
		entry = readdir(dir);
		if (!entry)
			break;
		name = strlen(entry->d_name);
		length = (19 + name + 1 + 7) & ~(size_t)7;
		if (used + length > size)
		{
			seekdir(dir, position);
			if (!used)
			{
				pthread_mutex_unlock(&dir_lock);
				return -22;
			}
			break;
		}
		*(uint64_t *)(out + used) = entry->d_ino;
		*(int64_t *)(out + used + 8) = telldir(dir);
		*(uint16_t *)(out + used + 16) = (uint16_t)length;
		out[used + 18] = entry->d_type; /* DT_* values agree */
		memcpy(out + used + 19, entry->d_name, name + 1);
		used += (uint32_t)length;
	}
	pthread_mutex_unlock(&dir_lock);
	return used;
}

/* ---------- futexes, on os_sync_wait_on_address */

static uint64_t ns_to_mach(uint64_t ns)
{
	static mach_timebase_info_data_t timebase;
	if (!timebase.denom)
		mach_timebase_info(&timebase);
	return ns * timebase.denom / timebase.numer;
}

static long futex_wake(void *address, int count)
{
	int woken = 0;
	if (count <= 0)
		return 0;
	if (count >= 0x7fffffff)
		return os_sync_wake_by_address_all(address, 4, OS_SYNC_WAKE_BY_ADDRESS_NONE) == 0 ? 1 : 0;
	while (woken < count && os_sync_wake_by_address_any(address, 4, OS_SYNC_WAKE_BY_ADDRESS_NONE) == 0)
		woken++;
	return woken;
}

static long futex(uint32_t address, int operation, uint32_t value, uint32_t timeout, uint32_t address2)
{
	void *host = G(void *, address);
	int command = operation & 127;
	switch (command)
	{
	case 0: /* FUTEX_WAIT */
	case 9: /* FUTEX_WAIT_BITSET (absolute timeout) */
	{
		struct timespec limit;
		int result;
		if (timespec_in(timeout, &limit))
		{
			int64_t ns = (int64_t)limit.tv_sec * 1000000000 + limit.tv_nsec;
			if (command == 9)
			{
				struct timespec now;
				clock_gettime((operation & 256) ? CLOCK_REALTIME : CLOCK_MONOTONIC, &now);
				ns -= (int64_t)now.tv_sec * 1000000000 + now.tv_nsec;
			}
			if (ns <= 0)
				return *(volatile uint32_t *)host == value ? -110 : -11;
			result = os_sync_wait_on_address_with_timeout(host, value, 4, OS_SYNC_WAIT_ON_ADDRESS_NONE,
				OS_CLOCK_MACH_ABSOLUTE_TIME, ns_to_mach((uint64_t)ns));
		}
		else
		{
			result = os_sync_wait_on_address(host, value, 4, OS_SYNC_WAIT_ON_ADDRESS_NONE);
		}
		if (result >= 0)
			return 0;
		if (errno == ETIMEDOUT) return -110;
		if (errno == EINTR) return -4;
		return 0; /* the value changed: a spurious return is allowed */
	}
	case 1: /* FUTEX_WAKE */
	case 10: /* FUTEX_WAKE_BITSET */
		return futex_wake(host, (int)value);
	case 3: /* FUTEX_REQUEUE */
	case 4: /* FUTEX_CMP_REQUEUE: wake everyone instead (spurious wakes are allowed) */
		futex_wake(G(void *, address2), 0x7fffffff);
		return futex_wake(host, 0x7fffffff);
	default:
		xg_log("futex operation %d is not supported", operation);
		return -38;
	}
}

/* ---------- clocks */

static clockid_t clock_in(long long l)
{
	switch (l)
	{
	case 0: case 5: return CLOCK_REALTIME;
	case 2: return CLOCK_PROCESS_CPUTIME_ID;
	case 3: return CLOCK_THREAD_CPUTIME_ID;
	case 4: return CLOCK_MONOTONIC_RAW;
	default: return CLOCK_MONOTONIC;
	}
}

static long sleep_for(const struct timespec *duration, uint32_t remaining)
{
	struct timespec left;
	if (nanosleep(duration, &left) == 0)
		return 0;
	timespec_out(remaining, &left);
	return -xg_linux_errno(errno);
}

/* ---------- dispatch */

long long xh_host_syscall(long long n, long long a, long long b, long long c, long long d, long long e, long long f)
{
	switch (n)
	{
	case LX_NR_write:
		if (a == 1 || a == 2)
		{
			console((int)a, G(const char *, b), (uint32_t)c);
			return (uint32_t)c;
		}
		return result_of(write((int)a, G(const void *, b), (uint32_t)c));
	case LX_NR_read: return result_of(read((int)a, G(void *, b), (uint32_t)c));
	case LX_NR_pread64: return result_of(pread((int)a, G(void *, b), (uint32_t)c, d));
	case LX_NR_pwrite64: return result_of(pwrite((int)a, G(const void *, b), (uint32_t)c, d));
	case LX_NR_writev: return vector_io((int)a, (uint32_t)b, (int)c, 0, 0, 1);
	case LX_NR_pwritev: return vector_io((int)a, (uint32_t)b, (int)c, d, 1, 1);
	case LX_NR_readv: return vector_io((int)a, (uint32_t)b, (int)c, 0, 0, 0);
	case LX_NR_preadv: return vector_io((int)a, (uint32_t)b, (int)c, d, 1, 0);
	case LX_NR_openat:
		return result_of(openat(dirfd_in(a), G(const char *, b), open_flags((int)c), (mode_t)d));
	case LX_NR_close:
		dir_forget((int)a);
		if (a <= 2)
			return 0;
		return result_of(close((int)a));
	case LX_NR_lseek: return result_of(lseek((int)a, b, (int)c));
	case LX_NR_getdents64: return getdents64((int)a, (uint32_t)b, (uint32_t)c);
	case LX_NR_unlinkat: return result_of(unlinkat(dirfd_in(a), G(const char *, b), at_flags((int)c)));
	case LX_NR_renameat:
	case LX_NR_renameat2:
		return result_of(renameat(dirfd_in(a), G(const char *, b), dirfd_in(c), G(const char *, d)));
	case LX_NR_mkdirat: return result_of(mkdirat(dirfd_in(a), G(const char *, b), (mode_t)c));
	case LX_NR_fchmod: return result_of(fchmod((int)a, (mode_t)b));
	case LX_NR_fchmodat: return result_of(fchmodat(dirfd_in(a), G(const char *, b), (mode_t)c, 0));
	case LX_NR_ftruncate: return result_of(ftruncate((int)a, b));
	case LX_NR_fsync:
	case LX_NR_fdatasync:
		return result_of(fsync((int)a));
	case LX_NR_fcntl:
		switch ((int)b)
		{
		case 0: return result_of(fcntl((int)a, F_DUPFD, (int)c));
		case 1030: return result_of(fcntl((int)a, F_DUPFD_CLOEXEC, (int)c));
		case 1: return result_of(fcntl((int)a, F_GETFD));
		case 2: return result_of(fcntl((int)a, F_SETFD, (int)c & 1));
		case 3:
		{
			int flags = fcntl((int)a, F_GETFL);
			return flags < 0 ? -xg_linux_errno(errno) : status_flags_out(flags);
		}
		case 4: return result_of(fcntl((int)a, F_SETFL, open_flags((int)c) & (O_APPEND | O_NONBLOCK)));
		default: return 0; /* record locks: one process */
		}
	case LX_NR_getcwd:
		if (!getcwd(G(char *, a), (uint32_t)b))
			return -xg_linux_errno(errno);
		return (long long)strlen(G(char *, a)) + 1;
	case LX_NR_chdir: return result_of(chdir(G(const char *, a)));
	case LX_NR_readlinkat: return result_of(readlinkat(dirfd_in(a), G(const char *, b), G(char *, c), (uint32_t)d));
	case LX_NR_faccessat: return result_of(faccessat(dirfd_in(a), G(const char *, b), (int)c, 0));
	case LX_NR_dup: return result_of(dup((int)a));
	case LX_NR_dup3: return result_of(dup2((int)a, (int)b));
	case LX_NR_pipe2:
	{
		int fds[2];
		if (pipe(fds))
			return -xg_linux_errno(errno);
		G(int32_t *, a)[0] = fds[0];
		G(int32_t *, a)[1] = fds[1];
		return 0;
	}
	case LX_NR_fstat:
	{
		struct stat s;
		if (fstat((int)a, &s))
			return -xg_linux_errno(errno);
		kstat_out((uint32_t)b, &s);
		return 0;
	}
	case LX_NR_newfstatat:
	{
		struct stat s;
		const char *path = G(const char *, b);
		int result = ((int)d & 0x1000) && !*path ? fstat((int)a, &s)
			: fstatat(dirfd_in(a), path, &s, at_flags((int)d));
		if (result)
			return -xg_linux_errno(errno);
		kstat_out((uint32_t)c, &s);
		return 0;
	}
	case LX_NR_utimensat:
	{
		struct timespec times[2];
		int index;
		if (c)
		{
			for (index = 0; index < 2; index++)
			{
				timespec_in((uint32_t)c + index * 8, &times[index]);
				if (times[index].tv_nsec == (1l << 30) - 1) times[index].tv_nsec = UTIME_NOW;
				else if (times[index].tv_nsec == (1l << 30) - 2) times[index].tv_nsec = UTIME_OMIT;
			}
		}
		return result_of(utimensat(dirfd_in(a), b ? G(const char *, b) : NULL, c ? times : NULL, at_flags((int)d)));
	}
	case LX_NR_clock_gettime:
	case LX_NR_clock_getres:
	{
		struct timespec value;
		int result = n == LX_NR_clock_gettime ? clock_gettime(clock_in(a), &value) : clock_getres(clock_in(a), &value);
		if (result)
			return -xg_linux_errno(errno);
		timespec_out((uint32_t)b, &value);
		return 0;
	}
	case LX_NR_gettimeofday:
	{
		struct timeval value;
		gettimeofday(&value, NULL);
		if (a)
		{
			G(int32_t *, a)[0] = (int32_t)value.tv_sec;
			G(int32_t *, a)[1] = (int32_t)value.tv_usec;
		}
		return 0;
	}
	case LX_NR_nanosleep:
	{
		struct timespec duration;
		if (!timespec_in((uint32_t)a, &duration))
			return -14;
		return sleep_for(&duration, (uint32_t)b);
	}
	case LX_NR_clock_nanosleep:
	{
		struct timespec duration;
		if (!timespec_in((uint32_t)c, &duration))
			return -14;
		if (b & 1) /* TIMER_ABSTIME */
		{
			struct timespec now;
			int64_t ns;
			clock_gettime(clock_in(a), &now);
			ns = ((int64_t)duration.tv_sec - now.tv_sec) * 1000000000 + duration.tv_nsec - now.tv_nsec;
			if (ns <= 0)
				return 0;
			duration.tv_sec = ns / 1000000000;
			duration.tv_nsec = ns % 1000000000;
			return sleep_for(&duration, 0);
		}
		return sleep_for(&duration, (uint32_t)d);
	}
	case LX_NR_futex: return futex((uint32_t)a, (int)b, (uint32_t)c, (uint32_t)d, (uint32_t)e);
	case LX_NR_ppoll:
	{
		struct timespec timeout;
		int ms = -1;
		if (timespec_in((uint32_t)c, &timeout))
			ms = (int)(timeout.tv_sec * 1000 + (timeout.tv_nsec + 999999) / 1000000);
		return result_of(poll(G(struct pollfd *, a), (nfds_t)(uint32_t)b, ms));
	}
	case LX_NR_mmap: return xg_guest_mmap((uint32_t)a, (uint32_t)b, (int)c, (int)d, (int)e, f);
	case LX_NR_munmap: return xg_guest_munmap((uint32_t)a, (uint32_t)b);
	case LX_NR_mprotect: return xg_guest_mprotect((uint32_t)a, (uint32_t)b, (int)c);
	case LX_NR_madvise: return 0;
	case LX_NR_mremap:
	case LX_NR_brk:
		return -12; /* musl then maps and copies */
	case LX_NR_exit:
	case LX_NR_exit_group:
		xh_host_exit((int)a);
	case LX_NR_set_tid_address:
	case LX_NR_gettid:
	{
		uint64_t id;
		pthread_threadid_np(NULL, &id);
		return (long long)(id & 0x3fffffff);
	}
	case LX_NR_getpid: return getpid();
	case LX_NR_getppid: return getppid();
	case LX_NR_getuid: return getuid();
	case LX_NR_geteuid: return geteuid();
	case LX_NR_getgid: return getgid();
	case LX_NR_getegid: return getegid();
	case LX_NR_umask: return umask((mode_t)a);
	case LX_NR_sched_yield: sched_yield(); return 0;
	case LX_NR_getrandom: arc4random_buf(G(void *, a), (uint32_t)b); return (uint32_t)b;
	case LX_NR_sched_getaffinity:
	{
		int cpus = 1;
		size_t length = sizeof(cpus);
		uint32_t index;
		sysctlbyname("hw.activecpu", &cpus, &length, NULL, 0);
		memset(G(void *, c), 0, (uint32_t)b);
		for (index = 0; index < (uint32_t)cpus && index / 8 < (uint32_t)b; index++)
			G(uint8_t *, c)[index / 8] |= (uint8_t)(1u << (index % 8));
		return (uint32_t)b < 8 ? (uint32_t)b : 8;
	}
	case LX_NR_uname:
	{
		char *u = G(char *, a);
		memset(u, 0, 65 * 6);
		strcpy(u, "Linux");
		strcpy(u + 65, "halopad");
		strcpy(u + 130, "6.0.0");
		strcpy(u + 195, "#1");
		strcpy(u + 260, "aarch64");
		return 0;
	}
	case LX_NR_kill:
	case LX_NR_tkill:
	case LX_NR_tgkill:
	{
		int signal = (int)(n == LX_NR_tgkill ? c : b);
		if (signal == 6)
			xg_fatal("the guest called abort()");
		return 0;
	}
	case LX_NR_flock:
	case LX_NR_membarrier:
	case LX_NR_rt_sigprocmask:
	case LX_NR_rt_sigaction:
	case LX_NR_sigaltstack:
		return 0;
	case LX_NR_ioctl: return -25; /* ENOTTY */
	case LX_NR_sysinfo:
	{
		/* struct sysinfo (ILP32): uptime, loads[3], totalram, freeram, ...,
		 * mem_unit at word 13 */
		uint32_t *info = G(uint32_t *, a);
		uint64_t memory = 0;
		size_t length = sizeof(memory);
		sysctlbyname("hw.memsize", &memory, &length, NULL, 0);
		memset(info, 0, 64);
		info[4] = (uint32_t)(memory >> 20);
		info[5] = (uint32_t)(memory >> 21);
		info[13] = 1u << 20;
		return 0;
	}
	default:
	{
		static uint8_t reported[512];
		if (n >= 0 && n < 512 && !reported[n])
		{
			reported[n] = 1;
			xg_log("guest system call %lld is not supported", n);
		}
		return -38;
	}
	}
}
