#!/usr/bin/env python3
"""Generate HaloPad's code page 1252 tables from Microsoft's published best-fit file.

Input: ref/inputs/nls/bestfit1252.txt (unicode.org MICSFT/WindowsBestFit, pinned by hash).
Output: generated/runtime/halopad_nls1252.h with
  * mb2wc[256]            byte -> UTF-16 (MBTABLE)
  * wc2mb[] (sorted)      UTF-16 -> byte, exact and best-fit entries (WCTABLE)
  * the default character (CPINFO)
  * ctype1 / upper / lower for every character a 1252 byte maps to: CT_CTYPE1 classes
    from Unicode general categories, with Windows XP-era overrides (below), and simple
    (one-to-one) Unicode case mappings; characters without one keep their value, as
    LCMapString does (it never expands, e.g. U+00DF).

Usage: scripts/gen-nls-tables.py [out.h]
"""
import hashlib
import pathlib
import re
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / 'ref' / 'inputs' / 'nls' / 'bestfit1252.txt'
SHA256 = '72ea23c939c5b26fae7aded0207b327e2f3902d7d3c168d7087f5cfc38ee76a9'
URL = 'https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WindowsBestFit/bestfit1252.txt'

# CT_CTYPE1 bits
UPPER, LOWER, DIGIT, SPACE, PUNCT, CNTRL, BLANK, XDIGIT, ALPHA = 1, 2, 4, 8, 0x10, 0x20, 0x40, 0x80, 0x100
# Windows XP-era classification differs from current Unicode for these characters
# (the classic Windows code page 1252 character-type table): the ordinal indicators are
# lowercase letters, superscript digits are digit+punctuation, modifier letters are
# punctuation.
OVERRIDES = {0x00AA: LOWER | ALPHA, 0x00BA: LOWER | ALPHA, 0x00B2: DIGIT | PUNCT, 0x00B3: DIGIT | PUNCT, 0x00B9: DIGIT | PUNCT}


def ctype1(w):
    if w in OVERRIDES:
        return OVERRIDES[w]
    c = chr(w)
    cat = unicodedata.category(c)
    x = XDIGIT if c in '0123456789abcdefABCDEF' else 0
    if cat == 'Lu': return UPPER | ALPHA | x
    if cat == 'Ll': return LOWER | ALPHA | x
    if cat in ('Lo', 'Lt'): return ALPHA
    if cat == 'Nd': return DIGIT | x
    if cat == 'Zs': return SPACE | BLANK
    if cat == 'Cc':
        if w == 9: return CNTRL | SPACE | BLANK
        if 10 <= w <= 13: return CNTRL | SPACE
        return CNTRL
    return PUNCT          # P*, S*, Lm, No, Cf


def simple(c, f):
    r = f(c)
    return ord(r) if len(r) == 1 else ord(c)


def main():
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'generated' / 'runtime' / 'halopad_nls1252.h'
    if not SRC.exists():
        sys.exit(f'missing {SRC}; fetch it: curl -sSfL -o {SRC} {URL}')
    data = SRC.read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA256:
        sys.exit(f'{SRC} does not match the pinned hash')
    text = data.decode('ascii', errors='replace')
    default = int(re.search(r'^CPINFO\s+1\s+(0x[0-9a-f]+)', text, re.M | re.I).group(1), 16)
    mb_part = text.split('MBTABLE', 1)[1].split('WCTABLE', 1)[0]
    wc_part = text.split('WCTABLE', 1)[1].split('ENDCODEPAGE', 1)[0]
    pair = re.compile(r'^(0x[0-9a-fA-F]+)\s+(0x[0-9a-fA-F]+)', re.M)
    mb = {int(a, 16): int(b, 16) for a, b in pair.findall(mb_part)}
    wc = sorted((int(a, 16), int(b, 16)) for a, b in pair.findall(wc_part))
    if len(mb) != 256:
        sys.exit(f'MBTABLE has {len(mb)} entries')
    domain = sorted(set(mb.values()))
    lines = ['/* Generated by scripts/gen-nls-tables.py from bestfit1252.txt (sha256 %s). Do not edit. */' % SHA256,
             '#include <stdint.h>',
             f'#define NLS1252_DEFAULT 0x{default:02x}',
             'static const uint16_t nls1252_mb2wc[256] = {' + ', '.join(f'0x{mb[i]:04x}' for i in range(256)) + '};',
             f'#define NLS1252_WC_COUNT {len(wc)}',
             'static const uint16_t nls1252_wc2mb[][2] = {' + ', '.join(f'{{0x{a:04x}, 0x{b:02x}}}' for a, b in wc) + '};',
             f'#define NLS1252_CHAR_COUNT {len(domain)}',
             '/* character, CT_CTYPE1, uppercase, lowercase (sorted by character) */',
             'static const uint16_t nls1252_chars[][4] = {' + ', '.join(
                 f'{{0x{w:04x}, 0x{ctype1(w):03x}, 0x{simple(chr(w), str.upper):04x}, 0x{simple(chr(w), str.lower):04x}}}'
                 for w in domain) + '};']
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines) + '\n')
    print(f'{out}: {len(wc)} WCTABLE entries, {len(domain)} characters')


if __name__ == '__main__':
    main()
