#!/usr/bin/env python3
"""Generate llasm wrappers for HaloPad's COM methods (G3).

Every C function in port/runtime/*.c named hpcom_<Interface>_<Method>_c(uint32_t ...),
and every HPCOM_FWDn(Interface, Method, impl) line, implements a COM method called by translated code as stdcall with 'this' first. This
writes generated/runtime/halopad-com.llasm with one wrapper per function, which passes
the stack arguments, sets eax and pops them. scripts/va-model.py includes it.

Usage: scripts/gen-com-wrappers.py [out.llasm]
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MACROS = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12}   # Call_Asm_StackN in asm-calls.llinc


def main():
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'generated' / 'runtime' / 'halopad-com.llasm'
    fns = {}
    for src in sorted((ROOT / 'port' / 'runtime').glob('*.c')):
        text = src.read_text()
        # HPCOM_FWDn(Interface, Method, impl): a method with n arguments after 'this' that
        # forwards to a shared implementation (halopad_win32.h)
        for m in re.finditer(r'^HPCOM_FWD(\d)\((\w+),\s*(\w+),', text, re.M):
            fns[f'hpcom_{m.group(2)}_{m.group(3)}'] = int(m.group(1)) + 1
        for m in re.finditer(r'^uint32_t (hpcom_\w+)_c\(([^)]*)\)\s*\{', text, re.M):
            params = [p for p in m.group(2).split(',') if p.strip() and p.strip() != 'void']
            if any(not p.strip().startswith('uint32_t') for p in params):
                sys.exit(f'{src.name}: {m.group(1)}_c takes non-uint32_t parameters')
            if len(params) not in MACROS:
                sys.exit(f'{src.name}: {m.group(1)}_c has {len(params)} parameters; no Call_Asm_Stack{len(params)} macro')
            fns[m.group(1)] = len(params)
    lines = [';; Generated by scripts/gen-com-wrappers.py. Do not edit.', '', 'include llasm.llinc', 'include asm-calls.llinc', '']
    lines += [f'func {n}_c ' + ', '.join(f'a{i + 1}' for i in range(k)) if k else f'func {n}_c' for n, k in sorted(fns.items())]
    for n, k in sorted(fns.items()):
        lines += ['', f'proc {n} public', f'        Call_Asm_Stack{k} {n}_c', f'        Call_Asm_Return {k}', 'endp']
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines) + '\n')
    print(f'{out}: {len(fns)} COM methods')


if __name__ == '__main__':
    main()
