#!/usr/bin/env python3
"""Build Xiph's libogg and libvorbis decoder (pinned in dependencies.lock.json) into a cached
static archive for a target, for HaloPad's vorbisfile.dll (port/runtime/halopad_vorbis.c).

    archive(target) -> path to generated/xiph/<target>/libhalopad-xiph.a
    include_flags() -> the -I flags for <vorbis/vorbisfile.h>
"""
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
OGG = ROOT / 'ref' / 'xiph' / 'ogg'
VORBIS = ROOT / 'ref' / 'xiph' / 'vorbis'
GEN = ROOT / 'generated' / 'xiph'
SOURCES = [OGG / 'src' / f for f in ('bitwise.c', 'framing.c')] + [VORBIS / 'lib' / f for f in (
    'mdct.c', 'smallft.c', 'block.c', 'envelope.c', 'window.c', 'lsp.c', 'lpc.c', 'analysis.c', 'synthesis.c', 'psy.c',
    'info.c', 'floor1.c', 'floor0.c', 'res0.c', 'mapping0.c', 'registry.c', 'codebook.c', 'sharedbook.c', 'lookup.c',
    'bitrate.c', 'vorbisfile.c')]
CONFIG_TYPES = '''/* Generated by scripts/xiph.py (libogg's config_types.h for HaloPad's targets). */
#ifndef __CONFIG_TYPES_H__
#define __CONFIG_TYPES_H__
#include <stdint.h>
#define INCLUDE_INTTYPES_H 1
#define INCLUDE_STDINT_H 1
#define INCLUDE_SYS_TYPES_H 1
typedef int16_t ogg_int16_t;
typedef uint16_t ogg_uint16_t;
typedef int32_t ogg_int32_t;
typedef uint32_t ogg_uint32_t;
typedef int64_t ogg_int64_t;
typedef uint64_t ogg_uint64_t;
#endif
'''


def include_flags():
    cfg = GEN / 'include' / 'ogg' / 'config_types.h'
    if not cfg.exists() or cfg.read_text() != CONFIG_TYPES:
        cfg.parent.mkdir(parents=True, exist_ok=True)
        cfg.write_text(CONFIG_TYPES)
    return ['-I', str(GEN / 'include'), '-I', str(OGG / 'include'), '-I', str(VORBIS / 'include')]


def archive(target, sysroot=None):
    if not (OGG / 'src' / 'framing.c').exists() or not (VORBIS / 'lib' / 'vorbisfile.c').exists():
        raise SystemExit('libogg/libvorbis are missing: run scripts/sources.py bootstrap')
    out = GEN / target
    lib = out / 'libhalopad-xiph.a'
    if lib.exists() and all(lib.stat().st_mtime >= s.stat().st_mtime for s in SOURCES):
        return lib
    out.mkdir(parents=True, exist_ok=True)
    objs = []
    for s in SOURCES:
        o = out / (s.parent.parent.name + '-' + s.stem + '.o')
        cmd = ['clang', '-target', target, '-O2', '-w', '-c', *include_flags(), '-I', str(VORBIS / 'lib'), str(s), '-o', str(o)]
        if sysroot:
            cmd[1:1] = ['-isysroot', sysroot]
        subprocess.run(cmd, check=True)
        objs.append(str(o))
    if lib.exists():
        lib.unlink()
    subprocess.run(['ar', 'rcs', str(lib), *objs], check=True)
    return lib


if __name__ == '__main__':
    import sys
    print(archive(sys.argv[1] if len(sys.argv) > 1 else 'arm64-apple-macosx14.0.0'))
