#!/usr/bin/env python3
"""Generate the host side of the guest's OpenGL ES imports (xg_gl_gen.c).

Reads the declarations upstream's generator wrote into the guest build's
guest_gl.c ("RET hostgl_glName(TYPES);") and emits, for each, a host function
xh_hostgl_glName that converts guest pointers (32-bit offsets into guest
memory) and calls the real function, resolved by xg_gl_load().

Usage: gen-host-gl.py <guest_gl.c> <out.c>
"""
import re
import sys

DECL = re.compile(r"^(.+?)\s*\bhostgl_(gl\w+)\((.*)\);$")
# pointer arguments that are buffer offsets, not addresses
OFFSETS = {("glVertexAttribPointer", 5), ("glVertexAttribIPointer", 4),
           ("glDrawElements", 3), ("glDrawElementsBaseVertex", 3)}
C_WORDS = {"long", "int", "char", "void", "unsigned", "short", "float", "double", "const", "signed"}


def param_type(text):
    """A parameter's type, without its name if it has one."""
    match = re.match(r"^(.*?[\s*])([A-Za-z_]\w*)$", text)
    if match and match.group(2) not in C_WORDS and not match.group(2).startswith("GL"):
        return match.group(1).strip()
    return text


def main():
    source, out = sys.argv[1], sys.argv[2]
    decls = []
    # the guest-side definitions keep each parameter's original type; the
    # hostgl_ declarations widen stack arguments (the ninth on) to long long,
    # which hides pointers among them
    original = {}
    for line in open(source):
        match = re.match(r"^static .*\bguest_(gl\w+)\((.*)\)$", line.strip())
        if match:
            params = match.group(2).strip()
            original[match.group(1)] = [] if params in ("", "void") else \
                [param_type(p.strip()) for p in params.split(",")]
    for line in open(source):
        if line[:1].isspace():
            continue
        match = DECL.match(line.strip())
        if match and "static" not in match.group(1) and match.group(1).strip() != "return":
            ret, name, params = match.group(1).strip(), match.group(2), match.group(3).strip()
            types = [] if params in ("", "void") else [param_type(p.strip()) for p in params.split(",")]
            decls.append((ret, name, types))
    lines = ["/* generated by scripts/xbox/gen-host-gl.py; do not edit */",
             '#include "xg_host.h"', "#include <GLES3/gl32.h>", "#include <stdlib.h>", "",
             "/* the platform's (xg_sdl.c, xg_ios.m) */",
             "void *xg_gl_proc(const char *name);",
             "GLuint xg_gl_framebuffer(GLuint framebuffer);", "",
             "/* XG_GL_CHECK=1: log the first OpenGL ES errors, naming the call */",
             "static int check_errors = -1;",
             "static GLenum (*check_get_error)(void);",
             "static void check(const char *name)",
             "{",
             "\tstatic int reported;",
             "\tGLenum error;",
             "\tif (check_errors < 0) { check_errors = getenv(\"XG_GL_CHECK\") != NULL; check_get_error = xg_gl_proc(\"glGetError\"); }",
             "\tif (!check_errors || reported > 40) return;",
             "\terror = check_get_error();",
             "\tif (error) { reported++; xg_log(\"OpenGL ES error 0x%x after %s\", error, name); }",
             "}", ""]
    loads = []
    for ret, name, types in decls:
        # the real function has the original types: upstream's widened stack
        # arguments are 8-byte slots on the guest side only (Apple's ABI packs
        # a 4-byte stack argument into 4 bytes)
        real = original.get(name, types)
        if len(real) != len(types):
            real = types
        lines.append("static %s (*p_%s)(%s);" % (ret, name, ", ".join(real) or "void"))
        params, args = [], []
        for index, t in enumerate(types):
            first = original.get(name, types)
            pointer = "*" in (first[index] if index < len(first) else t)
            rt = real[index]
            if name == "glShaderSource" and index == 2:
                params.append("uint32_t a%d" % index)
                args.append("(%s)strings" % rt)
            elif pointer and (name, index) in OFFSETS:
                params.append("uint32_t a%d" % index)
                args.append("(%s)(uintptr_t)a%d" % (rt, index))
            elif pointer and "*" in t:
                params.append("uint32_t a%d" % index)
                args.append("(%s)GP(a%d)" % (rt, index))
            elif pointer:
                # widened to a 64-bit stack slot: keep the slot, convert the value
                params.append("%s a%d" % (t, index))
                args.append("(%s)GP((uint32_t)a%d)" % (rt, index))
            else:
                params.append("%s a%d" % (t, index))
                args.append("(%s)a%d" % (rt, index) if rt != t else "a%d" % index)
        lines.append("%s xh_hostgl_%s(%s)" % (ret, name, ", ".join(params) or "void"))
        lines.append("{")
        if name == "glShaderSource":
            # upstream's guest widens the string pointers to 64 bits
            lines.append("\tconst GLchar *strings[16];")
            lines.append("\tGLsizei index;")
            lines.append("\tfor (index = 0; index < a1 && index < 16; index++)")
            lines.append("\t\tstrings[index] = GP((uint32_t)G(uint64_t *, a2)[index]);")
        if name == "glBindFramebuffer":
            # framebuffer 0 is the platform's drawable (a real framebuffer on iOS)
            args[1] = "xg_gl_framebuffer(a1)"
        if ret == "void":
            lines.append("\tp_%s(%s);" % (name, ", ".join(args)))
            if name != "glGetError":
                lines.append('\tif (check_errors) check("%s");' % name)
        elif name == "glGetError":
            lines.append("\treturn p_%s(%s);" % (name, ", ".join(args)))
        else:
            lines.append("\t%s result = p_%s(%s);" % (ret, name, ", ".join(args)))
            lines.append('\tif (check_errors) check("%s");' % name)
            lines.append("\treturn result;")
        lines.append("}")
        lines.append("")
        loads.append('\tp_%s = xg_gl_proc("%s");' % (name, name))
        loads.append('\tif (!p_%s) xg_log("OpenGL ES function %s is missing");' % (name, name))
    lines.append("void xg_gl_load(void)")
    lines.append("{")
    lines.extend(loads)
    lines.append("}")
    open(out, "w").write("\n".join(lines) + "\n")
    print("%d OpenGL ES imports" % len(decls))


if __name__ == "__main__":
    main()
