#!/usr/bin/env python3
"""Generate the host side of the guest's OpenGL ES imports (xg_gl_gen.c).

Reads the declarations upstream's generator wrote into the guest build's
guest_gl.c ("RET hostgl_glName(TYPES);") and emits, for each, a host function
xh_hostgl_glName that converts guest pointers (32-bit offsets into guest
memory) and calls the real function, resolved by xg_gl_load().

Usage: gen-host-gl.py <guest_gl.c> <out.c>
"""
import re
import sys

DECL = re.compile(r"^(.+?)\s*\bhostgl_(gl\w+)\((.*)\);$")
# pointer arguments that are buffer offsets, not addresses
OFFSETS = {("glVertexAttribPointer", 5), ("glVertexAttribIPointer", 4),
           ("glDrawElements", 3), ("glDrawElementsBaseVertex", 3)}
C_WORDS = {"long", "int", "char", "void", "unsigned", "short", "float", "double", "const", "signed"}


def param_type(text):
    """A parameter's type, without its name if it has one."""
    match = re.match(r"^(.*?[\s*])([A-Za-z_]\w*)$", text)
    if match and match.group(2) not in C_WORDS and not match.group(2).startswith("GL"):
        return match.group(1).strip()
    return text


def main():
    source, out = sys.argv[1], sys.argv[2]
    decls = []
    # the guest-side definitions keep each parameter's original type; the
    # hostgl_ declarations widen stack arguments (the ninth on) to long long,
    # which hides pointers among them
    original = {}
    for line in open(source):
        match = re.match(r"^static .*\bguest_(gl\w+)\((.*)\)$", line.strip())
        if match:
            params = match.group(2).strip()
            original[match.group(1)] = [] if params in ("", "void") else \
                [param_type(p.strip()) for p in params.split(",")]
    for line in open(source):
        if line[:1].isspace():
            continue
        match = DECL.match(line.strip())
        if match and "static" not in match.group(1) and match.group(1).strip() != "return":
            ret, name, params = match.group(1).strip(), match.group(2), match.group(3).strip()
            types = [] if params in ("", "void") else [param_type(p.strip()) for p in params.split(",")]
            decls.append((ret, name, types))
    lines = ["/* generated by scripts/xbox/gen-host-gl.py; do not edit */",
             '#include "xg_host.h"', "#include <GLES3/gl32.h>", "#include <SDL3/SDL.h>", ""]
    loads = []
    for ret, name, types in decls:
        lines.append("static %s (*p_%s)(%s);" % (ret, name, ", ".join(types) or "void"))
        params, args = [], []
        for index, t in enumerate(types):
            first = original.get(name, types)
            pointer = "*" in (first[index] if index < len(first) else t)
            if name == "glShaderSource" and index == 2:
                params.append("uint32_t a%d" % index)
                args.append("strings")
            elif pointer and (name, index) in OFFSETS:
                params.append("uint32_t a%d" % index)
                args.append("(%s)(uintptr_t)a%d" % (t, index))
            elif pointer and "*" in t:
                params.append("uint32_t a%d" % index)
                args.append("(%s)GP(a%d)" % (t, index))
            elif pointer:
                # widened to a 64-bit stack slot: keep the slot, convert the value
                params.append("%s a%d" % (t, index))
                args.append("(%s)(uintptr_t)GP((uint32_t)a%d)" % (t, index))
            else:
                params.append("%s a%d" % (t, index))
                args.append("a%d" % index)
        lines.append("%s xh_hostgl_%s(%s)" % (ret, name, ", ".join(params) or "void"))
        lines.append("{")
        if name == "glShaderSource":
            lines.append("\tconst GLchar *strings[16];")
            lines.append("\tGLsizei index;")
            lines.append("\tfor (index = 0; index < a1 && index < 16; index++)")
            lines.append("\t\tstrings[index] = GP(G(uint32_t *, a2)[index]);")
        lines.append("\t%sp_%s(%s);" % ("" if ret == "void" else "return ", name, ", ".join(args)))
        lines.append("}")
        lines.append("")
        loads.append('\tp_%s = (void *)SDL_GL_GetProcAddress("%s");' % (name, name))
        loads.append('\tif (!p_%s) xg_log("OpenGL ES function %s is missing");' % (name, name))
    lines.append("void xg_gl_load(void)")
    lines.append("{")
    lines.extend(loads)
    lines.append("}")
    open(out, "w").write("\n".join(lines) + "\n")
    print("%d OpenGL ES imports" % len(decls))


if __name__ == "__main__":
    main()
