/* HaloPad module services: GetModuleHandleA, LoadLibraryA, FreeLibrary, GetProcAddress (G3).
 *
 * The reference machine's modules are fixed. Handles are fixed addresses: the Windows
 * XP SP3 base address for the system DLLs whose base is documented here, otherwise an
 * address chosen by HaloPad (dinput8.dll and the game's own DLLs). Only strings.dll's
 * memory is mapped; code that reads another module's headers faults and names the address. "loaded" modules are present from process start; "loadable" ones
 * become loaded on LoadLibraryA (HaloPad provides their exports); "absent" ones are not
 * installed on the reference machine and fail with ERROR_MOD_NOT_FOUND, as on a real PC
 * without them. Any other module name stops the program.
 *
 * GetProcAddress resolves through the export registry generated by scripts/va-model.py:
 * every static and delay-load import plus config/runtime/dynamic-exports.txt. Each entry
 * has a guest address that dispatches to HaloPad's service or to a stub naming it. */
#include "halopad_win32.h"

#define ERROR_MOD_NOT_FOUND 126
enum { LOADED, LOADABLE, ABSENT, DATAFILE };
typedef struct { const char *name; uint32_t handle; int state; uint32_t refs; } module;

static module modules[] = {
    {"haloce.exe", HP_IMAGE_BASE, LOADED, 1},
    {"ntdll.dll", 0x7C900000, LOADED, 1},
    {"kernel32.dll", 0x7C800000, LOADED, 1},
    {"user32.dll", 0x7E410000, LOADED, 1},
    {"gdi32.dll", 0x77F10000, LOADED, 1},
    {"advapi32.dll", 0x77DD0000, LOADED, 1},
    {"ole32.dll", 0x774E0000, LOADED, 1},
    {"oleaut32.dll", 0x77120000, LOADED, 1},
    /* delay-loaded and dynamically loaded modules HaloPad provides */
    {"ws2_32.dll", 0x71AB0000, LOADABLE, 0},
    {"wsock32.dll", 0x71AD0000, LOADABLE, 0},
    {"dsound.dll", 0x73F10000, LOADABLE, 0},
    {"winmm.dll", 0x76B40000, LOADABLE, 0},
    {"shell32.dll", 0x7C9C0000, LOADABLE, 0},
    {"wininet.dll", 0x3D930000, LOADABLE, 0},
    {"version.dll", 0x77C00000, LOADABLE, 0},
    {"shfolder.dll", 0x76780000, LOADABLE, 0},      /* SHGetFolderPathA (My Documents) */
    {"d3d9.dll", 0x4FDD0000, LOADABLE, 0},
    {"dinput8.dll", 0x4C000000, LOADABLE, 0},
    {"vorbisfile.dll", 0x10000000, LOADABLE, 0},   /* shipped with the game */
    {"binkw32.dll", 0x10100000, LOADABLE, 0},      /* shipped with the game */
    {"eula.dll", 0x10200000, LOADABLE, 0},         /* shipped with the game */
    /* game DLLs Halo uses only for resources: mapped as read-only images from the game
       directory at their preferred base; their code never runs (no DllMain; no dispatch
       entries, so any transfer into them traps with the address) */
    {"strings.dll", 0x3F800000, DATAFILE, 0},
    /* not installed on the reference machine */
    {"mscoree.dll", 0, ABSENT, 0},                 /* no .NET runtime */
    {"nvcpl.dll", 0, ABSENT, 0},                   /* no NVIDIA control panel */
};
#define NMOD (sizeof modules / sizeof modules[0])

extern const uint32_t halopad_import_count, halopad_import_base, halopad_import_stride;
extern const char *const halopad_import_names[];
extern const char *const halopad_import_dlls[];

static void normalize(const char *in, char *out, size_t size)
{
    const char *base = in;
    for (const char *p = in; *p; p++) if (*p == '\\' || *p == '/') base = p + 1;
    size_t n = 0;
    for (; base[n] && n + 1 < size; n++) out[n] = (char)(base[n] >= 'A' && base[n] <= 'Z' ? base[n] + 32 : base[n]);
    out[n] = 0;
    if (!strchr(out, '.') && n + 5 < size) strcat(out, ".dll");   /* Windows appends .dll */
}

static module *find_module(const char *service, uint32_t name_ptr)
{
    char n[260];
    normalize(G(name_ptr), n, sizeof n);
    for (size_t i = 0; i < NMOD; i++) if (!strcmp(modules[i].name, n)) return &modules[i];
    hp_unsupported(service, "module \"%s\"", (const char *)G(name_ptr));
}

uint32_t GetModuleHandleA_c(uint32_t name)
{
    if (!name) return HP_IMAGE_BASE;
    module *m = find_module("GetModuleHandleA", name);
    if (m->state == LOADED) return m->handle;
    halopad_last_error = ERROR_MOD_NOT_FOUND;
    return 0;
}

static uint32_t mapped[8];
static uint32_t nmapped;

uint32_t halopad_module_mapped(uint32_t handle)
{
    if (handle == HP_IMAGE_BASE) return 1;
    for (uint32_t i = 0; i < nmapped; i++) if (mapped[i] == handle) return 1;
    return 0;
}

uint32_t VirtualProtect_c(uint32_t address, uint32_t size, uint32_t prot, uint32_t old);

/* Lay out a PE file's headers and sections at its preferred base, as the Windows loader
   does, then make the whole image read-only. No relocation is needed at the preferred
   base, no imports are bound and no entry point runs. */
static void map_datafile(module *m)
{
    const char *root = getenv("HALOPAD_GAME_ROOT");
    if (!root) hp_unsupported("LoadLibraryA", "no HALOPAD_GAME_ROOT for \"%s\"", m->name);
    char path[1024];
    snprintf(path, sizeof path, "%s/%s", root, m->name);
    FILE *f = fopen(path, "rb");
    if (!f) hp_unsupported("LoadLibraryA", "cannot open %s", path);
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    uint8_t *file = malloc((size_t)size);
    fseek(f, 0, SEEK_SET);
    if (fread(file, 1, (size_t)size, f) != (size_t)size) hp_unsupported("LoadLibraryA", "short read of %s", path);
    fclose(f);
    uint32_t pe, image_size, headers, nsec, opt;
    memcpy(&pe, file + 0x3C, 4);
    memcpy(&image_size, file + pe + 0x50, 4);
    memcpy(&headers, file + pe + 0x54, 4);
    nsec = (uint32_t)(file[pe + 6] | file[pe + 7] << 8);
    opt = (uint32_t)(file[pe + 0x14] | file[pe + 0x15] << 8);
    if (halopad_vm_reserve(m->handle, image_size, 1) != m->handle)
        hp_unsupported("LoadLibraryA", "preferred base 0x%08x of %s is not free", m->handle, m->name);
    memcpy(G(m->handle), file, headers);
    for (uint32_t i = 0; i < nsec; i++) {
        const uint8_t *sh = file + pe + 0x18 + opt + 40 * i;
        uint32_t va, raw, rawptr;
        memcpy(&va, sh + 12, 4); memcpy(&raw, sh + 16, 4); memcpy(&rawptr, sh + 20, 4);
        if (raw) memcpy(G(m->handle + va), file + rawptr, raw);
    }
    free(file);
    VirtualProtect_c(m->handle, image_size, 0x02 /* PAGE_READONLY */, 0);
    mapped[nmapped++] = m->handle;
}

uint32_t LoadLibraryA_c(uint32_t name)
{
    module *m = find_module("LoadLibraryA", name);
    if (m->state == ABSENT) { halopad_last_error = ERROR_MOD_NOT_FOUND; return 0; }
    if (m->state == DATAFILE) map_datafile(m);
    m->state = LOADED;
    m->refs++;
    return m->handle;
}

/* Modules stay loaded; the reference count is kept for FreeLibrary's result only. */
uint32_t FreeLibrary_c(uint32_t handle)
{
    for (size_t i = 0; i < NMOD; i++)
        if (modules[i].handle == handle && modules[i].state == LOADED) { if (modules[i].refs) modules[i].refs--; return 1; }
    halopad_last_error = HP_ERROR_INVALID_HANDLE;
    return 0;
}

/* Exports that do not exist on the reference machine (Windows XP SP3): GetProcAddress
 * returns NULL with ERROR_PROC_NOT_FOUND, and callers take their fallback path. */
static const char *const absent_exports[] = {
    "kernel32.dll!FlsAlloc", "kernel32.dll!FlsFree", "kernel32.dll!FlsGetValue", "kernel32.dll!FlsSetValue",   /* Vista+ */
};

uint32_t GetProcAddress_c(uint32_t handle, uint32_t name)
{
    const module *m = NULL;
    for (size_t i = 0; i < NMOD; i++) if (modules[i].handle == handle && modules[i].state == LOADED) m = &modules[i];
    if (!m) hp_unsupported("GetProcAddress", "module handle 0x%08x", handle);
    char want[64];
    if (name < 0x10000) snprintf(want, sizeof want, "#%u", name);
    else snprintf(want, sizeof want, "%s", (const char *)G(name));
    for (uint32_t i = 0; i < halopad_import_count; i++)
        if (!strcmp(halopad_import_dlls[i], m->name) && !strcmp(halopad_import_names[i], want))
            return halopad_import_base + halopad_import_stride * i;
    char full[128];
    snprintf(full, sizeof full, "%s!%s", m->name, want);
    for (size_t i = 0; i < sizeof absent_exports / sizeof absent_exports[0]; i++)
        if (!strcmp(absent_exports[i], full)) { halopad_last_error = 127; /* ERROR_PROC_NOT_FOUND */ return 0; }
    hp_unsupported("GetProcAddress", "%s!%s (add it to config/runtime/dynamic-exports.txt)", m->name, want);
}

void InitializeCriticalSection_c(uint32_t cs);
uint32_t InitializeCriticalSectionAndSpinCount_c(uint32_t cs, uint32_t spin)
{
    (void)spin;                         /* spinning is a performance hint */
    InitializeCriticalSection_c(cs);
    return 1;
}
