/* HaloPad guest memory and dispatch (G2e, original-address model).
 *
 * Guest addresses are Halo's own 32-bit addresses. A 4 GiB region is reserved with no
 * access, so every 32-bit guest address lands inside it: unmapped addresses (including
 * the null page) fault, and the fault handler reports them as guest addresses. Only
 * the image, a guest stack and a guest heap are made readable and writable. Nothing is
 * mapped executable; all control flow goes to procedures compiled ahead of time. */
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#define PTROFS_64BIT 1
#include "llasm_cpu.h"
extern _Thread_local _cpu *halopad_cpu;

#define HOST_RETURN_VA 0xFFFFF000u
#define GUEST_SPAN ((uint64_t)1 << 32)

uint64_t halopad_guest_base;
/* The slice harness takes argument buffers from a bump heap; the core leaves this 0
 * and allocates through the Windows memory services instead. */
int halopad_guest_harness_heap = 1;
static uint32_t heap_next, heap_end;

extern const uint32_t halopad_dispatch_count;
extern const uint32_t halopad_dispatch_vas[];
extern void *const halopad_dispatch_fns[];
extern void *halopad_return_to_host_address(void);
/* halopad_callback.c: host entry levels; level k returns through sentinel HOST_RETURN_VA + 16k */
#define HALOPAD_MAX_ENTRY_LEVELS 64
void *halopad_host_return(uint32_t level);
/* Import binding (generated by scripts/va-model.py): every static import has a fixed
 * guest address in a never-mapped page; Halo's import address table gets these. */
extern const uint32_t halopad_import_count, halopad_import_slot_count, halopad_import_base, halopad_import_stride;
extern const uint32_t halopad_import_slots[];
extern const char *const halopad_import_names[];
extern const uint32_t halopad_com_base, halopad_com_method_count;
extern const char *const halopad_com_methods[];

void halopad_trace_guest_stack(void);
static void guest_fault(int sig, siginfo_t *info, void *ctx)
{
    (void)ctx;
    uint64_t a = (uint64_t)(uintptr_t)info->si_addr;
    if (halopad_guest_base && a >= halopad_guest_base && a < halopad_guest_base + GUEST_SPAN)
        fprintf(stderr, "HALOPAD FAULT: guest access to 0x%08x (signal %d)\n", (uint32_t)(a - halopad_guest_base), sig);
    else
        fprintf(stderr, "HALOPAD FAULT: host address %p (signal %d)\n", info->si_addr, sig);
    halopad_trace_guest_stack();                                    /* diagnostics only; not async-signal-safe */
    _exit(70);
}

static void commit(uint32_t guest, uint32_t size)
{
    long page = sysconf(_SC_PAGESIZE);
    uint64_t lo = (uint64_t)guest & ~(uint64_t)(page - 1);
    uint64_t hi = ((uint64_t)guest + size + page - 1) & ~(uint64_t)(page - 1);
    if (mprotect((void *)(uintptr_t)(halopad_guest_base + lo), hi - lo, PROT_READ | PROT_WRITE) != 0) {
        perror("HALOPAD: mprotect");
        exit(2);
    }
}

/* Reserve guest memory, load the prepared image at its original address, and set up a
 * guest stack and heap. Returns the guest stack top. */
uint32_t halopad_guest_init(const char *image_path, uint32_t image_base)
{
    void *base = mmap(NULL, GUEST_SPAN, PROT_NONE, MAP_PRIVATE | MAP_ANON, -1, 0);
    if (base == MAP_FAILED) { perror("HALOPAD: reserving guest address space"); exit(2); }
    halopad_guest_base = (uint64_t)(uintptr_t)base;
    FILE *f = fopen(image_path, "rb");
    if (!f) { perror(image_path); exit(2); }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    commit(image_base, (uint32_t)size);
    if (fread((void *)(uintptr_t)(halopad_guest_base + image_base), 1, (size_t)size, f) != (size_t)size) {
        fprintf(stderr, "HALOPAD: short read of %s\n", image_path);
        exit(2);
    }
    fclose(f);
    commit(0x00100000, 0x00200000);            /* guest stack: 0x00100000-0x00300000 */
    if (halopad_guest_harness_heap) {
        heap_next = 0x10000000; heap_end = 0x20000000;
        commit(heap_next, heap_end - heap_next);   /* guest heap for harness buffers */
    }
    struct sigaction sa;
    memset(&sa, 0, sizeof sa);
    sa.sa_sigaction = guest_fault;
    sa.sa_flags = SA_SIGINFO;
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGBUS, &sa, NULL);
    /* Bind the import address table: slot i holds import i's guest address. */
    for (uint32_t i = 0; i < halopad_import_slot_count; i++) {
        uint32_t v = halopad_import_base + halopad_import_stride * i;
        memcpy((void *)(uintptr_t)(halopad_guest_base + halopad_import_slots[i]), &v, 4);
    }
    return 0x00300000 - 0x100;
}

uint32_t halopad_guest_alloc(uint32_t size, uint32_t align)
{
    uint32_t a = (heap_next + align - 1) & ~(align - 1);
    if (a + size > heap_end) { fprintf(stderr, "HALOPAD: guest heap exhausted\n"); exit(2); }
    heap_next = a + size;
    return a;
}

void *halopad_guest_ptr(uint32_t guest) { return (void *)(uintptr_t)(halopad_guest_base + guest); }

/* Make a guest range readable and writable (runtime-owned structures). Returns guest. */
uint32_t halopad_guest_commit(uint32_t guest, uint32_t size)
{
    commit(guest, size);
    return guest;
}

/* For traps: the guest registers and the top of the guest stack. Inside a service the top
   holds the service's return address into the calling guest code, then its arguments. */
void halopad_trace_guest_stack(void)
{
    if (!halopad_cpu || !halopad_guest_base) return;
    uint32_t sp = halopad_cpu->_esp, words[8];
    memcpy(words, (void *)(uintptr_t)(halopad_guest_base + sp), sizeof words);
    fprintf(stderr, "  guest esp=0x%08x ebp=0x%08x ecx=0x%08x eax=0x%08x; stack:", sp, halopad_cpu->_ebp, halopad_cpu->_ecx, halopad_cpu->_eax);
    for (int k = 0; k < 8; k++) fprintf(stderr, " %08x", words[k]);
    fprintf(stderr, "\n");
    /* callers through the frame-pointer chain (code built with frame pointers) */
    fprintf(stderr, "  frames:");
    uint32_t fp = halopad_cpu->_ebp;
    for (int k = 0; k < 12 && fp && fp < 0xFFFF0000u && fp >= sp; k++) {
        uint32_t link[2];
        memcpy(link, (void *)(uintptr_t)(halopad_guest_base + fp), sizeof link);
        fprintf(stderr, " %08x", link[1]);
        if (link[0] <= fp) break;
        fp = link[0];
    }
    fprintf(stderr, "\n");
}

/* x87 results wider than a register (llasm_float.c): translated code reads them through the
   returned address, so they are copied to a per-thread slot in guest memory. */
uint32_t halopad_heap_alloc(uint32_t size, int zero);
static _Thread_local uint32_t x87_slot;
uint32_t halopad_x87_result(_cpu *cpu, const int64_t *value)
{
    (void)cpu;
    if (!x87_slot) x87_slot = halopad_heap_alloc(8, 1);
    memcpy((void *)(uintptr_t)(halopad_guest_base + x87_slot), value, 8);
    return x87_slot;
}

/* Original address -> compiled procedure (finite table generated at build time). */
/* HALOPAD_WATCH=va[,va...] (diagnostics only): print the return address and first arguments
   whenever an indirect call or jump reaches one of these addresses (COM methods, callbacks). */
static uint32_t watch_vas[16], watch_count;
static uint32_t watch_range[4];   /* HALOPAD_WATCH_RANGE=to_lo:to_hi:from_lo:from_hi (hex): transfers into one module from another */
__attribute__((constructor)) static void watch_init(void)
{
    const char *w = getenv("HALOPAD_WATCH");
    while (w && *w && watch_count < 16) {
        char *end;
        watch_vas[watch_count++] = (uint32_t)strtoul(w, &end, 16);
        w = *end ? end + 1 : end;
    }
    const char *r = getenv("HALOPAD_WATCH_RANGE");
    if (r && sscanf(r, "%x:%x:%x:%x", &watch_range[0], &watch_range[1], &watch_range[2], &watch_range[3]) == 4 && !watch_count)
        watch_count = 1, watch_vas[0] = 0xFFFFFFFFu;
}
static void watch(uint32_t va)
{
    if (watch_range[1] && va >= watch_range[0] && va < watch_range[1]) {
        uint32_t s[6];
        memcpy(s, (void *)(uintptr_t)(halopad_guest_base + halopad_cpu->_esp), sizeof s);
        if (s[0] >= watch_range[2] && s[0] < watch_range[3])
            fprintf(stderr, "HALOPAD WATCH: 0x%08x from 0x%08x (%08x %08x %08x %08x %08x)\n", va, s[0], s[1], s[2], s[3], s[4], s[5]);
        return;
    }
    for (uint32_t i = 0; i < watch_count; i++)
        if (watch_vas[i] == va) {
            uint32_t s[6];
            memcpy(s, (void *)(uintptr_t)(halopad_guest_base + halopad_cpu->_esp), sizeof s);
            fprintf(stderr, "HALOPAD WATCH: 0x%08x from 0x%08x (%08x %08x %08x %08x %08x) eax=%08x esp=%08x\n", va, s[0], s[1], s[2], s[3], s[4], s[5], halopad_cpu->_eax, halopad_cpu->_esp);
        }
}

void *halopad_lookup(uint32_t va)
{
    if (__builtin_expect(watch_count != 0, 0)) watch(va);
    uint32_t lo = 0, hi = halopad_dispatch_count;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2;
        uint32_t v = halopad_dispatch_vas[mid];
        if (v == va) return halopad_dispatch_fns[mid];
        if (v < va) lo = mid + 1; else hi = mid;
    }
    if (va >= HOST_RETURN_VA && va < HOST_RETURN_VA + 16 * (HALOPAD_MAX_ENTRY_LEVELS + 1) && !(va & 15))
        return halopad_host_return((va - HOST_RETURN_VA) / 16);
    if (va >= halopad_import_base && va < halopad_import_base + halopad_import_stride * halopad_import_count) {
        uint32_t i = (va - halopad_import_base) / halopad_import_stride;
        fprintf(stderr, "HALOPAD TRAP: indirect transfer to 0x%08x, inside import %s's address but not its entry\n",
                va, halopad_import_names[i]);
        abort();
    }
    if (va >= halopad_com_base && va < halopad_com_base + halopad_import_stride * halopad_com_method_count) {
        fprintf(stderr, "HALOPAD TRAP: indirect transfer to 0x%08x, inside COM method %s's address but not its entry\n",
                va, halopad_com_methods[(va - halopad_com_base) / halopad_import_stride]);
        abort();
    }
    fprintf(stderr, "HALOPAD TRAP: indirect transfer to 0x%08x, which has no compiled procedure\n", va);
    halopad_trace_guest_stack();
    abort();
}
